name: vertretungsapp
description: Deine Vertretungsplanapp fÃ¼r Indiware
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  google_fonts: ^5.1.0
  intl: ^0.18.1
  date_format: ^2.0.7
  http: ^1.1.0
  xml2json: ^6.1.0
  dart_date: ^1.2.2
  font_awesome_flutter: ^10.5.0
  flutter_secure_storage: ^8.0.0
  flutter_launcher_icons: ^0.13.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
